[tool.ruff]
line-length = 88
extend-exclude = ["tic80/python/game.py"]

[tool.ruff.lint]
select = [
  "E", "F",
  "B",
  "ISC",
  "UP",
]

ignore = ["UP035"]

[tool.ruff.lint.flake8-implicit-str-concat]
allow-multiline = false